import streamlit as st

st.set_page_config(
    page_title="Hello",
    page_icon="👋",
)

st.write("# Welcome to Motion's SIGMOD Demo! 👋")

st.sidebar.success("Select a mode of exploration.")

st.markdown(
    """
    Motion is a framework that enables LLM pipeline developers to define and incrementally maintain self-updating prompts in Python.
    **👈 Select a mode of exploration** to either interact with a Motion-powered application or explore prompt sub-parts generated by Motion.
    ### Explore our AI Stylist Application
    - Interact with our example application where an AI stylist suggests items to buy for events of your choice, powered by Motion.
    ### Explore Prompt Sub-Parts and Real-Time Prompt Updates
    - Explore the prompt sub-parts generated by Motion and see how they dynamically update as new information becomes available.
    ### Want to learn more about Motion?
    - Visit [Motion's github repo](https://github.com/dm4ml/motion)
    - Dive into our [documentation](https://dm4ml.github.io/motion/docs)
    ### Origin of Motion
    - Developed by the UC Berkeley EPIC Lab.
"""
)
